#!/bin/bash

function build_openh264() {(
    cd openh264
    patch -p1 -N -r - <<EOF
diff --git a/Makefile b/Makefile
index 63dc1cd..281b9bc 100644
--- a/Makefile
+++ b/Makefile
@@ -42,7 +42,7 @@ endif
 # Configurations
 ifeq (\$(BUILDTYPE), Release)
 CFLAGS += \$(CFLAGS_OPT)
-USE_ASM = Yes
+USE_ASM = No
 else
 CFLAGS = \$(CFLAGS_DEBUG)
 USE_ASM = No
diff --git a/codec/common/src/WelsThreadLib.cpp b/codec/common/src/WelsThreadLib.cpp
index 9366807..3f24801 100644
--- a/codec/common/src/WelsThreadLib.cpp
+++ b/codec/common/src/WelsThreadLib.cpp
@@ -487,8 +487,8 @@ WELS_THREAD_ERROR_CODE    WelsQueryLogicalProcessInfo (WelsLogicalProcessInfo* p

   size_t len = sizeof (pInfo->ProcessorCount);

-  if (sysctlbyname (HW_NCPU_NAME, &pInfo->ProcessorCount, &len, NULL, 0) == -1)
-    pInfo->ProcessorCount = 1;
+  //if (sysctlbyname (HW_NCPU_NAME, &pInfo->ProcessorCount, &len, NULL, 0) == -1)
+  pInfo->ProcessorCount = 1;

   return WELS_THREAD_ERROR_OK;
EOF
    emmake make clean
    emmake make -j4
)}

function build_x264() {(
    cd x264
    emconfigure ./configure --disable-cli --enable-static --disable-opencl \
                --disable-thread --disable-interlaced \
                --chroma-format=420 --disable-asm
    emmake make clean
    emmake make -j4
)}

function build_libvpx() {(
    cd libvpx
    emconfigure ./configure \
                --target=generic-gnu \
                --disable-multithread --disable-examples --disable-docs \
                --disable-md5
    sed -i -e "s/HAVE_GNU_STRIP=yes/HAVE_GNU_STRIP=no/" libs-generic-gnu.mk
    sed -i -e "s/^ARFLAGS =.*$/ARFLAGS = rusc/" libs-generic-gnu.mk
    emmake make clean
    emmake make -j4
)}

build_openh264
build_x264
build_libvpx
